# Generated by Django 2.2 on 2019-04-16 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombineVericle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_full_name', models.CharField(max_length=50)),
                ('borrower_addredd', models.TextField(blank=True, null=True)),
                ('borrower_city', models.CharField(max_length=30)),
                ('borrower_state', models.CharField(max_length=10)),
                ('borrower_zip_code', models.IntegerField()),
                ('serial_number', models.CharField(max_length=20)),
                ('primary_loan_cs_registration_payment_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_last_paid_date', models.DateTimeField(blank=True, null=True)),
                ('account_total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_status', models.CharField(choices=[('R', ''), ('P', ''), ('O', '')], max_length=2)),
                ('acctual_days_past_due', models.IntegerField(default=0)),
                ('actual_payment_past_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_due_ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_data', models.DateTimeField(blank=True, null=True)),
                ('last_event_date', models.DateTimeField(auto_now=True)),
                ('collateral_recovery_device', models.CharField(max_length=20)),
                ('collateral_year_model', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2019)])),
                ('collateral_make', models.CharField(max_length=24)),
                ('collateral_model', models.CharField(max_length=24)),
                ('collateral_stock_number', models.CharField(max_length=10)),
                ('collateral_vin', models.CharField(blank=True, max_length=32, null=True)),
                ('latitue', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('last_out_for_repo_date', models.DateTimeField(blank=True, null=True)),
                ('actual_record_flags', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='signature',
            field=models.ImageField(upload_to='signature/16-04-2019-09-04'),
        ),
    ]
