# Generated by Django 2.2 on 2019-04-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190416_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinevericle',
            name='borrower_addredd',
            field=models.CharField(max_length=255),
        ),
    ]
