# Generated by Django 2.2 on 2019-04-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190416_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinevericle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Driver'),
        ),
        migrations.AlterField(
            model_name='combinevericle',
            name='borrower_addredd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='combinevericle',
            name='borrower_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='combinevericle',
            name='borrower_state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='combinevericle',
            name='borrower_zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combinevericle',
            name='last_event_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='combinevericle',
            name='latitue',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='combinevericle',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='combinevericle',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
