# Generated by Django 2.2 on 2019-04-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190417_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='signature',
            field=models.ImageField(upload_to='signature/17-04-2019-09-04'),
        ),
    ]
