# Generated by Django 2.2 on 2019-04-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190417_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='signature',
            field=models.ImageField(upload_to='signature/20-04-2019-19-04'),
        ),
    ]
